apiVersion: apps/v1
kind: Deployment
metadata:
  name: arm64
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arm64
  template:
    metadata:
      labels:
        app: arm64
    spec:
      securityContext:
        runAsUser: 2000
        runAsGroup: 3000
        fsGroup: 2000
      containers:
      - image: public.ecr.aws/eks-distro/kubernetes/pause:3.2
        name: arm64
        resources:
          requests:
            cpu: "1"
            memory: 256M
        securityContext:
          allowPrivilegedEscalation: false
      nodeSelector:
        kubernetes.io/arch: arm64