name: CI
on:
  push:
    branches:
      - 'main'
      - 'release-v*'
      - 'staging/*'
  pull_request:
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    if: github.repository == 'aws/karpenter-provider-aws'
    steps:
    - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
    - uses: ./.github/actions/install-deps
    - name: Enable the actionlint matcher
      run: echo "::add-matcher::.github/actionlint-matcher.json"
    - run: make ci-non-test
